add ios ci

diff --git a/.github/workflows/iOS_ci.yml b/.github/workflows/iOS_ci.yml
--- a/.github/workflows/iOS_ci.yml
+++ b/.github/workflows/iOS_ci.yml
@@ -66,18 +66,18 @@ jobs:
           flutter devices
           nohup flutter run -d "$IOS_SIM_UDID" --debug --verbose > flutter_run.log 2>&1 &
           echo $! > flutter_run.pid
-          sleep 90
+          sleep 180
           flutter logs -d "$IOS_SIM_UDID" --verbose > flutter_logs.log 2>&1 &
           echo $! > flutter_logs.pid
-          sleep 30
+          sleep 180
 
       - name: Print Logs
         if: always()
         run: |
           echo "===== flutter_run.log ====="
-          [ -f flutter_run.log ] && sed -n '1,300p' flutter_run.log || echo "flutter_run.log not found"
+          [ -f flutter_run.log ] && tail -n 1000 flutter_run.log || echo "flutter_run.log not found"
           echo "===== flutter_logs.log ====="
-          [ -f flutter_logs.log ] && sed -n '1,300p' flutter_logs.log || echo "flutter_logs.log not found"
+          [ -f flutter_logs.log ] && tail -n 1000 flutter_logs.log || echo "flutter_logs.log not found"
 
       - name: Stop Background Processes
         if: always()
